feat(#96): Multiple plans -> one time paiement
For-Hives/ForVoyez pull request #137
Opened 2024-05-14 15:27 UTC by CinquinAndy

- Added logging for plans and variants
- Updated filtering logic for subscription and one-time plans

2024-05-20 17:03 UTC, LightInn commented on src/services/webhook.service.js
> +	const customerId = parsed_webhook.meta.custom_data.user_id
tu confond customer_id et user_id ici 🤔  
le customer_id est donner dans le corps (attributes) du webhook et est generer/gerer par lemonsqueezy, contrairement au user_id gerer par clerk dont lemon se fiche eperduement

2024-05-20 17:04 UTC, LightInn commented on src/services/webhook.service.js
> +				clerkId: customerId,
du coup ici, ca rends le code tres confus

2024-05-20 17:08 UTC, LightInn commented on src/services/webhook.service.js
> +	const customerId = webhook.meta.custom_data.user_id
same

2024-05-20 17:34 UTC, LightInn commented on src/services/webhook.service.js
> +				// Update the user's credits by adding the credits difference using the updateCreditForUser function
il a payer les deux ? il devrais pas avoir le credits des deux ?

2024-05-20 18:29 UTC, CinquinAndy commented on src/services/webhook.service.js
> +				// Update the user's credits by adding the credits difference using the updateCreditForUser function
nah car dans lemon, ça fait la différence du prix des deux
Exemple: 
tu prend le plan 1 : -4€ + 100 crédits
tu prend le plan 2 : -30€ + 1000 crédits

Mais si tu fais : 
plan 1 -> changement vers plan 2 : ça fait -26€ ... donc on veut donner les crédits de la différence des deux

2024-05-20 18:29 UTC, CinquinAndy commented on src/services/webhook.service.js
> +	const customerId = webhook.meta.custom_data.user_id
mb, je change ça

2024-05-20 18:29 UTC, CinquinAndy commented on src/services/webhook.service.js
> +				clerkId: customerId,
mb, je change ça

2024-05-20 18:29 UTC, CinquinAndy commented on src/services/webhook.service.js
> +	const customerId = parsed_webhook.meta.custom_data.user_id
mb, je change ça

2024-05-20 18:29 UTC, CinquinAndy commented on src/services/database.service.js
> +		)
mb, je change ça

2024-05-20 18:30 UTC, CinquinAndy commented on prisma/schema.prisma
> +  plan Plan @relation(fields: [planId], references: [id])
hummm nah c'est moi qui ai fait une bétise dans les millions de changement, je réfléchi je te dirais pourquoi mdr, et si ça sert à R, je supp

2024-05-20 18:31 UTC, CinquinAndy commented on src/components/Dashboard/ChangingPlans.component.js
> +		getPlans().then(plans => {
on a pas le même pricing en fonction du plan actuel : 
![image](https://github.com/For-Hives/ForVoyez/assets/55706543/d4535e94-0012-4465-bd30-5e344551a864)

![image](https://github.com/For-Hives/ForVoyez/assets/55706543/bd7cb2b5-90d4-42e8-beec-3d6f9b7f9adc)
&&
![image](https://github.com/For-Hives/ForVoyez/assets/55706543/b0ffc3e5-5a52-4b19-9eed-20a01989bd1e)

2024-05-20 18:33 UTC, CinquinAndy commented on src/components/Playground/Playground.component.js
> +		if (value.length > 750) {
pour réduire les coûts maximum des requêtes, le context est utilisé dans la première requête vers bobby 4o, 
Sauf que ça coute grave cher, donc pour rester dans des prix raisonnable en prenant en compte les taxes etc... j'ai essayer de réduire ce que je pouvais

2024-05-20 18:34 UTC, CinquinAndy commented on src/components/usage/usageChart.component.js
> +	// console.table(usage)
ah merde, il faut que je change tout ça alors, 
je vais avoir un autre soucis avec le playground à mon avis, faut que je regarde

2024-05-20 18:35 UTC, CinquinAndy commented on src/components/Playground/Playground.component.js
> +	const handlePourcentLenghtSize = (text, limit) => {
handle pourcent lenght size
handle le pourcentage de la taille

on a un compteur de caractère en mode "character remaining" , on j'ai une fonction qui va venir calculer à combien de % on est rendu dans la saisie , pour afficher une couleur différente, 
tu veux que je l'appelle comment ?

2024-05-21 09:23 UTC, LightInn commented on prisma/schema.prisma
> +  plan Plan @relation(fields: [planId], references: [id])
D'accord 🤔

2024-05-21 13:53 UTC, CinquinAndy commented on prisma/schema.prisma
> +  plan Plan @relation(fields: [planId], references: [id])
![image](https://github.com/For-Hives/ForVoyez/assets/55706543/2eaf60f8-24e5-437f-9553-498d6be2578b)

Alors c'est une subscription qui peut être lié à un plan du coup, pour récupérer le nom du parent (pour les variants) dans lemonSqueezy, 

Tu avais l'impression que c'était lié à Plan à cause de gituhb qui à fait ligne 45 - 75 caché mdr

2024-05-21 14:03 UTC, CinquinAndy commented on src/services/database.service.js
> +		)
fixed

2024-05-21 14:05 UTC, CinquinAndy commented on src/services/webhook.service.js
> +				// Update the user's credits by adding the credits difference using the updateCreditForUser function
yesss

2024-05-21 14:05 UTC, CinquinAndy commented on src/services/webhook.service.js
> +				// Update the user's credits by adding the credits difference using the updateCreditForUser function
Mais ça posait un gros soucis, si la personne achetais un gros plan, genre 100€, après il pouvais changer de plan & buy des plans en boucle à 0€ sans frais mdr, et en même temps rechargé ses crédits (lourd la faille)

2024-05-21 14:42 UTC, CinquinAndy commented on src/components/Playground/Playground.component.js
> +	const handlePourcentLenghtSize = (text, limit) => {
"determineTextColorBasedOnLength"

2024-05-21 15:36 UTC, LightInn requested changes
nerby the end <3

2024-05-21 15:36 UTC, LightInn commented on src/components/Dashboard/ChangingPlans.component.js
> +			sortAndSetPlans(plans, setPlans)
en rentrant le setPlan dans la fonction de tris, tu melange les responsabilité de la fonctions, et tu cache le mechanisme de changement d'etat :thinking:  c'est pas une bonne pratique je pense, faudrait faire un 
```suggestion
			setPlans(plans.map(sortAndSetPlans))
```

2024-05-21 15:36 UTC, LightInn commented on src/services/database.service.js
> +			productName: variant.productName,
du coup la fonction _addVariant na plus besoin de deuxieme parametre 
![image](https://github.com/For-Hives/ForVoyez/assets/28759336/c12aadcd-2644-4785-8ddd-326905929f73)

2024-05-21 15:36 UTC, LightInn commented on src/utils/sortAndSetPlans.js
je suis peut etre un peu maniqo depressif sur ce point la, mais je n'aime pas du tout `utils`; je trouve que ca a tendance a se transformer en depotoir a fichier random quand la codbase evolue 

on pourrais avoir un nom plus structuer comme "helpers" ou "shared"

2024-05-21 15:39 UTC, LightInn requested changes

2024-05-21 15:39 UTC, LightInn commented on src/components/Playground/Playground.component.js
> +		if (value.length > 750) {
genre tu coupe quoi exactement ? c'est quoi "editor" ? 
genre le schema que tu limite ?

2024-05-21 15:40 UTC, LightInn commented on src/components/Playground/Playground.component.js
> +		if (value.length > 750) {
genre tu coupe quoi exactement ? c'est quoi "editor" ?
genre le schema que tu limite ?

2024-05-22 07:24 UTC, CinquinAndy commented on src/utils/sortAndSetPlans.js
bah shared ou utils c'est la même chose, mais je renomme ça en helpers si ça te fais plaisir ♥

2024-05-22 08:56 UTC, CinquinAndy commented on src/components/Playground/Playground.component.js
> +		if (value.length > 750) {
les éditors, c'est ça : 
""
![image](https://github.com/For-Hives/ForVoyez/assets/55706543/169d7464-3897-4501-8e88-8403af316d7c)

""

Je limite juste la taille du texte dispo, donc là, en l'occurence, le context, et le schéma
Le schéma ça coute quasi rien de le changer, c'est plus le conexte qui est "cher" 

Car le schéma ça applique ça sur la deuxième requête qui coute genre 0.001 centime

2024-05-22 09:09 UTC, LightInn approved these changes
run&gun

2024-05-22 09:10 UTC, merged