Feat/tests
For-Hives/ForVoyez pull request #224
Opened 2024-06-03 18:57 UTC by CinquinAndy

Lot's of things, fixes, improvments, and 90% of e2e tests

2024-06-03 19:20 UTC, CinquinAndy commented
tout le reste normalement c'est bon, 

il faudra parcontre, faire des scripts pour séparer les runs des tests, du tests e2e pour tester le playground, (pour éviter de devoir payer pour rien)

2024-06-03 19:21 UTC, CinquinAndy commented
-> faut que je regarde pourquoi les tests casses aussi sur la pipeline

2024-06-04 09:27 UTC, LightInn commented
> tout le reste normalement c'est bon,
> 
> il faudra parcontre, faire des scripts pour séparer les runs des tests, du tests e2e pour tester le playground, (pour éviter de devoir payer pour rien)

tu a fait des tests payant ?

2024-06-04 09:33 UTC, LightInn commented
> -> faut que je regarde pourquoi les tests casses aussi sur la pipeline

pour le moment, je pense que pnpm a pas aimer le downgrade de ta version : 
![image](https://github.com/For-Hives/ForVoyez/assets/28759336/b7055990-4787-42e6-bcf1-8b6510ad3997)

2024-06-04 09:35 UTC, CinquinAndy commented
> > tout le reste normalement c'est bon,
> > il faudra parcontre, faire des scripts pour séparer les runs des tests, du tests e2e pour tester le playground, (pour éviter de devoir payer pour rien)
> 
> tu a fait des tests payant ?

-> juste le playground du coup

2024-06-05 15:09 UTC, CinquinAndy commented
@LightInn normalement, tout est bon, je pense tu vas me taper sur la partie ci / cd , mais j'en ai trop chié ( sans faire de préprod c'est la merde les tests e2e )

2024-06-05 15:10 UTC, WadeFade commented
> @LightInn normalement, tout est bon, je pense tu vas me taper sur la partie ci / cd , mais j'en ai trop chié ( sans faire de préprod c'est la merde les tests e2e )

il est à 2 doigts de delete la branche xD

2024-06-07 15:24 UTC, LightInn requested changes
Bon, j'ai essayer de pas trop faire le vieux con, je peux me tromper ou pas tout comprendre, j'ai essayer de faire attentions a un max de truc mais j'ai peut etre loupe des trucs; en tout cas je proposes des choses que je pense pas trop connes 


sinon, j'ai pas regarder tout les tests e2e en details, mais j'ai fait le focus sur les plus longs; au moins je poste ca pour que tu puisse avancer; deso pour le nombre de commentaires, j'avais des choses a dire :heart:

2024-06-07 15:24 UTC, LightInn commented on tests/e2e/e2e-general/app-general/app-nav.spec.js
> +	test('Sidebar internal links navigate correctly', async ({ page }) => {
je pense pas que ce tests soit utile, ca tests juste la capaciter du navigateur a changer de page, mais ca ne tests pas notre application a proprement parler, le tests precedant verifier quil y a une balise <a> avec le bon href. je ne suis pas sur que c'est vraiment interessant de tester le comportement standard du navigateur

2024-06-07 15:24 UTC, LightInn commented on tests/e2e/e2e-general/app-general/app-nav.spec.js
> +	test('Sidebar external links have correct href', async ({ page }) => {
tu a deja tester le externalLink dans le premier test, tests inutile (c'est pas mal, on gratte deux tests sur un des fichier les plus long a s'executer )

2024-06-07 15:24 UTC, LightInn commented on tests/e2e/tests-utils.js
> +export const signIn = async (
hum, il faut qu'on trouve si il y a pas un moyen d'opti a more cette methode, car elle est appeller dans presque tout les tests et elle coute 3secondes en moyennes; j'ai regarder vite fait et il ya moyen de mettre en place des histoire de cache / de browser contexte pour "devenir" connecter a chaque fois plus rapidemenent. car on s'en fiche de tester la connexion a chaque fois. 

il y a cette doc officiel qui a l'aire de faire ce qu'on veut : https://playwright.dev/docs/auth


ps : je note ca la, mais au court ce cette revue, je me rends compte que toi ou claude, jsp, a un nouveau tick de programations, vous adorer mettre des fonctions de forme `const foo = () => {}`  partout, il y en avais dans tout les fichier

2024-06-07 15:24 UTC, LightInn commented on tests/e2e/e2e-general/app-general/app-dashboard.spec.js
c'est aussi un des fichier les plus lourds en temps a tester, c'est c'est une copie comforme de app-nav.spec, il ne test rien de nouveau, il peut etre degager

2024-06-07 15:56 UTC, CinquinAndy commented on package.json
> +		"test:e2e:premium": "playwright test tests/e2e/e2e-premium"
je l'avais fait dans le sens où je me suis dit qu'on pouvait avoir trois possibilitées , soit on veux run tout les tests et mettre le paquet 
Soit on veux run juste les généraux et pas les "prémium" pour pas payer
Soit on veux run les prémium pour juste tester ça de manière isolé aussi

2024-06-07 15:58 UTC, CinquinAndy commented on package.json
> +		"start": "next start -H 0.0.0.0",
est ce que c'est génant ? tu penses qu'on devrait le virer ? en soit, perso, il m'arrange (car besoin de faire des tests sur 15 écrans mdr)

2024-06-07 15:59 UTC, CinquinAndy commented on .env.exemple
> +TEST_PASSWORD_SUB=your-test-password
okayy, j'ai passé le nom du test à "sub"

2024-06-07 15:59 UTC, CinquinAndy commented on .env.exemple
> +TEST_PASSWORD_SUB=your-test-password
"test:e2e:sub": "playwright test tests/e2e/e2e-sub"

2024-06-07 16:00 UTC, CinquinAndy commented on .github/workflows/tests.yml
> +name: 'Test and Deploy'
alors c'est très vrai ce que tu dis , (j'avoue le jeudi soir était compliqué et claude à fait des bétises, jsuis une merde mdr)

2024-06-07 16:02 UTC, CinquinAndy commented on .github/workflows/tests.yml
> +      - '*'
je crée juste une issue pour refactor ça alors

2024-06-07 16:03 UTC, CinquinAndy commented on .github/workflows/tests.yml
>    test:
j'ai mit 'unit-test' pour garder la cohérence français - anglais

2024-06-07 16:05 UTC, CinquinAndy commented on .github/workflows/tests.yml
> +        run: pnpm exec playwright install
effectivement my bad, je l'ai pas virer, c'est fait maintenant

2024-06-07 16:06 UTC, CinquinAndy commented on .github/workflows/tests.yml
> +    needs: test
done

2024-06-07 16:07 UTC, CinquinAndy commented on .github/workflows/tests.yml
> +          pnpm install -g gulp prettier vitest
effectivement

2024-06-07 16:09 UTC, CinquinAndy commented on .github/workflows/tests.yml
> +            --build-arg ENABLE_TEST_LOGS=${{ secrets.ENABLE_TEST_LOGS }} \
bah, j'y ai passé une journée entière, j'ai jamais réussi à le faire fonctionner sans, si tu arrives à trouver une solution, je suis preneur, je fais une issue pour refactor ça du coup, mais j'ai aucune idée de comment faire, 
le build de next n'a jamais réussi à trouver les bons liens & les bonnes variables d'env à chaque fois :(

2024-06-07 16:11 UTC, CinquinAndy commented on .github/workflows/tests.yml
> +          docker build -f Dockerfile.test -t my-app:test \
done

2024-06-07 16:12 UTC, CinquinAndy commented on .github/workflows/tests.yml
> +          docker run -d --entrypoint="" --name my-app-container -p 3000:3000 \
l'image arrive pas à démarrer / build correctement sans ça de souvenir 
Tu penses que virer le entrypoint impact par le start de l'app ? j'essaye pour voir

2024-06-07 16:14 UTC, CinquinAndy commented on .github/workflows/tests.yml
> +            -e ENABLE_TEST_LOGS=${{ secrets.ENABLE_TEST_LOGS }} \
Effectivement, même chose, je crée une issue, c'est pas "important" pour le moment (de ce que t'en penses?)

2024-06-07 16:20 UTC, CinquinAndy commented on .github/workflows/tests.yml
> +          docker run -d --entrypoint="" --name my-app-container -p 3000:3000 \
![image](https://github.com/For-Hives/ForVoyez/assets/55706543/3dd8db7c-36a2-4c52-af1a-855e7f36937b)

Effectivement ça fonctionne pas quand je l'enleve

2024-06-07 16:21 UTC, CinquinAndy commented on .github/workflows/tests.yml
> +          docker logs my-app-container
hummm ça se tiens, ça se tiens, je le vire

2024-06-07 16:26 UTC, CinquinAndy commented on .github/workflows/tests.yml
> +          exit 1
j'ai mit à 10s ça suffit effectivement

2024-06-07 16:27 UTC, CinquinAndy commented on .github/workflows/tests.yml
> +          docker rm my-app-container
done

2024-06-07 16:28 UTC, CinquinAndy commented on Dockerfile.prod
pareil, ça va avec l'autre, j'ai jamais réussi à faire fonctionner sans ça ;(

2024-06-07 16:37 UTC, CinquinAndy commented on Dockerfile.test
> +ENTRYPOINT ["pnpm", "run", "launch"]
effectivement en modifiant ça, ça passe la pipeline du commentaire d'ne haut

2024-06-07 16:38 UTC, CinquinAndy commented on .github/workflows/tests.yml
> +          docker run -d --entrypoint="" --name my-app-container -p 3000:3000 \
-> avec un des commentaire en dessous, ça fonctionne

2024-06-07 16:38 UTC, CinquinAndy commented on .github/workflows/tests.yml
> +          docker run -d --entrypoint="" --name my-app-container -p 3000:3000 \
(done)

2024-06-07 16:39 UTC, CinquinAndy commented on Dockerfile.test
> +ENTRYPOINT ["pnpm", "run", "launch"]
ah bah non mdr

2024-06-07 16:40 UTC, CinquinAndy commented on build_docker_scripts/buid.sh
effectivement, c'était pour faire mes tests en local & éviter 5 minutes entre chaque essai, je vire ça

2024-06-07 16:40 UTC, CinquinAndy commented on build_docker_scripts/build.ps1
bahahhaha

2024-06-07 16:41 UTC, CinquinAndy commented on error-screenshot.png
ah oui ça c'est très vrai

2024-06-07 16:44 UTC, CinquinAndy commented on package.json
> +		"dotenv": "16.4.5",
alooors, ouii, mais je vais avoir besoin d'un coup de main sur la pipeline, il ne veux pas build avec les trucs de dev, et ne pas planter si je luii donne les trucs de dev ;(

2024-06-07 16:47 UTC, CinquinAndy commented on playwright.config.js
> +	workers: 1,
j'ai des soucis lié au spaming de lemon je pense, ou à des soucis de requête concurrente (je crois, quie c'est à cause du fait que pas mal de de test doivent être fait avec un identifiant logique et valide, et que clerk invalide les autres connexion lorsqu'on se connecte depuis une autre source)

2024-06-07 16:48 UTC, CinquinAndy commented on playwright.config.js
> +	workers: 1,
j'ai créer une autre issue pour ça

2024-06-07 16:50 UTC, CinquinAndy commented on pnpm-lock.yaml
wtfff la version de pnpm local a un impact ??! wtf ? 

effectivmeent j'ai mis à jour mon pnpm ça a régler ce soucis, wtffff
(done)

2024-06-07 16:51 UTC, CinquinAndy commented on public/1x1.webp
mdrrrrrrr cette phrase est trop belle, ( sohyun.png me foudroie )

2024-06-07 16:52 UTC, CinquinAndy commented on public/1x1.webp
(done)

2024-06-07 16:54 UTC, CinquinAndy commented on src/components/Dashboard/ChangingPlans.component.js
> +	const [loadingUrls, setLoadingUrls] = useState(true) // New state to track URL loading status
effectivement
(done)

2024-06-09 13:41 UTC, CinquinAndy commented on src/components/Dashboard/ChangingPlans.component.js
> +	const [loadingUrls, setLoadingUrls] = useState(true) // New state to track URL loading status
(done), j'ai corriger ça du coup

2024-06-09 13:42 UTC, CinquinAndy commented on src/components/Dashboard/ChangingPlans.component.js
>  	const router = useRouter()
done

2024-06-09 13:42 UTC, CinquinAndy commented on src/components/Dashboard/ChangingPlans.component.js
> +			setLoadingUrls(false)
done

2024-06-09 13:45 UTC, CinquinAndy commented on src/services/lemonsqueezy.service.js
> +import { createCheckout, listCheckouts } from '@lemonsqueezy/lemonsqueezy.js'
done

2024-06-09 13:46 UTC, CinquinAndy commented on src/services/lemonsqueezy.service.js
> +export async function getCheckouts(plans) {
done

2024-06-09 13:47 UTC, CinquinAndy commented on src/services/lemonsqueezy.service.js
> +	const check = await listCheckouts({
done

2024-06-09 13:58 UTC, CinquinAndy commented on src/services/lemonsqueezy.service.js
> +		},
humz :( 
cette partie m'emmerde, 
Effectivement ça peut visiblement poser problème, bah, je vais revenir à la version d'avant hein

2024-06-09 14:13 UTC, CinquinAndy commented on src/services/lemonsqueezy.service.js
> +		},
en gros, pour expliquer, ça fonctionne comme ça actuellement : 
"""
	console.log('---------------- check.data.meta')
	console.log(check.data.meta)
"""

```
---------------- check.data.meta
{
  page: {
    currentPage: 1,
    from: 1,
    lastPage: 17,
    perPage: 100,
    to: 100,
    total: 1691
  }
}
```

en gros, le truc qui me chagrine actuellement, c'est que pour chaque chargement de page, on demande à LemonSqueezy de créer une page de checkout avec des données custom, pour chaque abonnement et chaque variant...
Donc 1 utilisateur - 1 chargement => ~ 10 checkouts créés

2024-06-09 14:22 UTC, LightInn commented on src/services/lemonsqueezy.service.js
> +		},
Mais dans la version d'encore avant (celle sur dev, pas celle de ta branche) on creer le checkout seulement au moment ou l'utilisateur clique sur le bouton de subscribe, et il doit attendre 1seconde de plus certe, mais ca me parait raisonable 
On avait pas de soucis de spam

je ne suis pas certain que ce soit vraiment utile de vouloir absolument precharger les liens, surtout que ca n'aporte aucune info de referencement ou quoi

2024-06-09 14:36 UTC, CinquinAndy commented on src/services/lemonsqueezy.service.js
> +		},
![image](https://github.com/For-Hives/ForVoyez/assets/55706543/42a83671-2092-4fab-b688-3230f4840d50)

ça fait comme solution, on reviens comme avant, mais en plus de ça, on met juste une limite au temps de checkout

2024-06-09 14:36 UTC, CinquinAndy commented on src/services/lemonsqueezy.service.js
> +		},
(done)

2024-06-09 14:37 UTC, LightInn commented on package.json
> +		"start": "next start -H 0.0.0.0",
nan tkt c'est pas genant x')

2024-06-09 14:39 UTC, CinquinAndy commented on src/services/webhook.service.js
> -			// Get the new plan associated with the current subscription
done

2024-06-09 14:40 UTC, LightInn commented on .github/workflows/tests.yml
> +            -e ENABLE_TEST_LOGS=${{ secrets.ENABLE_TEST_LOGS }} \
Ouais, je me mettrais sur la ci pour la refactor

2024-06-09 14:41 UTC, LightInn commented on package.json
> +		"dotenv": "16.4.5",
je regarderais ca en refacto la ci

2024-06-09 14:41 UTC, CinquinAndy commented on src/services/database.service.js
> +export async function getCurrentUser() {
sauf que t'as méthodes que tu avais fait avant faisant planté le front :(

2024-06-09 14:48 UTC, CinquinAndy commented on src/services/database.service.js
> +				!product.relationships.variants.data
done

2024-06-09 14:50 UTC, CinquinAndy commented on src/services/database.service.js
>  	}
done

2024-06-09 14:52 UTC, CinquinAndy commented on src/services/database.service.js
> -	// Fetch usage data for the user, including the associated token
done

2024-06-09 14:52 UTC, CinquinAndy commented on src/services/database.service.js
>  	}
done

2024-06-09 14:53 UTC, CinquinAndy commented on src/services/database.service.js
>  	}
done

2024-06-09 14:55 UTC, CinquinAndy commented on src/services/database.service.js
>  }
#219 , alors, j'ai bien compris que le fait que j'ai viré ton code t'as véxer, (mdr) , vu que t'as mis 5 commentaires dessus, mais j'ai essayer de régler soucis et j'y suis pas arrivé, c'est pour ça que j'avais créer une issue là dessus 
Je te laisserai regarder et corriger le soucis, car j'ai aps envie de passer 2h dessus alors que la méthode proposer crée une erreur avec nextjs

2024-06-09 15:01 UTC, CinquinAndy commented on src/components/usage/usageChart.component.js
> +			Promise.all([fetchUsage(), fetchUsageByToken()]).finally(() => {
bah justement, c'était plus jolis et plus sympa d'afficher le skeleton tant que le fetch était pas fini des deux côté, je trouve, c'était juste un trick volontaire pour que ça soit plus sympa en terme de visuel

Et on dit que le promise.all est une mauvaise pratique car elle lie des trucs qui devrait pas l'être en théorie et empeche les resultats partiels, 
Sauf que ici c'est volontaire, si les deux données sotn pas chargés, c'est que nos données sotn pas valides, (même si le fetch est vide hein) 
ça permet d'afficher deux skeletons de graphique en même temps et éviter que la page "saute" en pleins milieu

2024-06-09 15:02 UTC, CinquinAndy commented on src/components/Dashboard/RefillPlans.component.js
> +	if (plans.length === 0 || isLoadingUrls) {
done

2024-06-09 15:03 UTC, CinquinAndy commented on tests/unit/services/lemonsqueezy.test.js
> +	getCheckouts,
done

2024-06-09 15:04 UTC, CinquinAndy commented on tests/unit/services/jwt.test.js
> +			)
mdr, elle est chimique effectivement

2024-06-09 15:05 UTC, CinquinAndy commented on tests/unit/services/database.test.js
> +					userId: userId,
nah c'est mon ide qui m'a fait un caca boudin

2024-06-09 15:08 UTC, CinquinAndy commented on tests/e2e/tests-utils.js
done

2024-06-09 15:08 UTC, CinquinAndy commented on .github/workflows/tests.yml
> +            --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
yes, ça se tiens, je fais une issue, je ferais ça :d

2024-06-09 15:12 UTC, CinquinAndy commented on src/services/database.service.js
> +					!variantDetails.data.data.attributes
done

2024-06-09 15:13 UTC, CinquinAndy commented on tests/unit/services/database.test.js
> +	getCurrentUser, // Import getCurrentUser directly
mdr, done

2024-06-09 15:17 UTC, CinquinAndy commented on tests/e2e/e2e-general/app-general/app-nav.spec.js
> +	test('Sidebar external links have correct href', async ({ page }) => {
tu penses que "juste" le check de si la balise à la bon lien ça suffit, pas besoin de check la navigation ?

2024-06-09 15:18 UTC, CinquinAndy commented on tests/e2e/e2e-general/app-general/app-nav.spec.js
> +	test('Sidebar external links have correct href', async ({ page }) => {
j'ai delete les deux parties de tests autre que le check de la balise basique

2024-06-09 15:19 UTC, CinquinAndy commented on tests/e2e/tests-utils.js
> +export const signIn = async (
bah ui j'aime bien, c'est joli mdr

2024-06-09 15:21 UTC, CinquinAndy commented on tests/e2e/e2e-general/app-general/app-dashboard.spec.js
je test les liens oui, mais les liens des card dans la partie dashboard , donc pas le même truc exactement que la partie "nav"

2024-06-09 15:24 UTC, LightInn commented on src/services/database.service.js
>  }
Bah ce qui ma "vexer" c'est que je pensais que tu avait juste fait un copier coller claude vue qu'il y avait le commentaire claude....  mais my bad du coup, j'avais pas vue que ça pétait un truc ailleurs

2024-06-09 15:33 UTC, LightInn commented on tests/e2e/e2e-general/app-general/app-nav.spec.js
> +	test('Sidebar external links have correct href', async ({ page }) => {
Et bien je pense pas que ce soit interessant de tester qu'un navigateur arrive a ouvrir une balise a avec un href. je veux dire, c'est le comportement standard d'un navigateur, si il est pas capable de le faire un moment on y peut rien x') 
donc tester que le href est bon me semble suffisant, en plus tester les lien externe c'est risquer dans dans tests car il ne se retrouve plus completement isoler de l'exterieur, il se mette a dependre de si les elements exterieur marche (on a regulierement le probleme sur my-makeup ou des tests front casse car l'api preprod tombe, ce qui rends les tests non truhsty )

2024-06-09 15:45 UTC, LightInn commented on tests/e2e/e2e-general/app-general/app-dashboard.spec.js
ah my bad, j'avais l'impression que cetais exactement les memes liens

2024-06-09 15:50 UTC, LightInn commented on tests/e2e/tests-utils.js
> +export const signIn = async (
je met ca dans une issue urgente histoire de le faire rapidement :p

2024-06-09 15:55 UTC, LightInn approved these changes
Bon, je te propose d'achever cette mr record.... et je prie pour ne plus jamais en voir de tel 😢

2024-06-09 17:19 UTC, merged