Feat: #Dashboard
For-Hives/ForVoyez pull request #57
Opened 2024-05-05 14:31 UTC by CinquinAndy

- #50
- #56
- #48

2024-05-05 15:28 UTC, LightInn requested changes

2024-05-05 15:28 UTC, LightInn commented on src/components/AccountComponents/LayoutAccount.component.js
> +			<SectionProviderAccountComponent sections={[]}>
Un commentaire qui part

2024-05-05 15:28 UTC, LightInn commented on src/components/AccountComponents/NavigationAccount.component.js
> +			className={clsx(
l'accronyme est encore trop comprehensible je trouve

2024-05-05 15:28 UTC, LightInn commented on src/components/AccountComponents/RemToPxAccount.component.js
Dans le dossier component, avec des fichier qui finissent en ".component.js", est ce que c'est necessaire d'appeler le dossier cible "AccountComponents" ? c'est plus simple avec juste "Account" nan ? (c'est pas une question en faite)

2024-05-05 15:28 UTC, LightInn commented on src/components/AccountComponents/ResourceCardAccount.component.js
> +	let maskImage = useMotionTemplate`radial-gradient(180px at ${mouseX}px ${mouseY}px, white, transparent)`
wtf??? c'est quoi cette chose ?

2024-05-05 15:28 UTC, LightInn commented on src/components/LandingComponents/ClientComponent.component.js
c'est gerer dans le middleware ca

2024-05-05 16:10 UTC, CinquinAndy commented on src/components/AccountComponents/ResourceCardAccount.component.js
> +	let maskImage = useMotionTemplate`radial-gradient(180px at ${mouseX}px ${mouseY}px, white, transparent)`
on regardera

2024-05-05 16:10 UTC, CinquinAndy commented on src/components/LandingComponents/ClientComponent.component.js
(la redirection vers la connexion)

2024-05-06 01:32 UTC, CinquinAndy commented on src/components/AccountComponents/ResourceCardAccount.component.js
> +	let maskImage = useMotionTemplate`radial-gradient(180px at ${mouseX}px ${mouseY}px, white, transparent)`
La syntaxe utilisée ici, avec les backticks et ${}, est appelée "tagged template literals" en JavaScript. Elle permet de définir une chaîne de template qui peut contenir des expressions JavaScript évaluées dynamiquement.

2024-05-06 01:35 UTC, CinquinAndy commented
all done

2024-05-06 10:45 UTC, LightInn approved these changes

2024-05-06 11:11 UTC, merged